{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_allure_report.py:11: AssertionError"}, "description": "this test fails", "start": 1618283519749, "stop": 1618283519749, "uuid": "2e518d2d-be89-406a-90b2-d82958f2025b", "historyId": "86e9c0c683f1fe1c2e1f41f486f1583d", "testCaseId": "cc74f89b669144905de0c227d37fd59a", "fullName": "test_allure_report#test_failure", "labels": [{"name": "suite", "value": "test_allure_report"}, {"name": "host", "value": "摩羯座"}, {"name": "thread", "value": "7992-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure_report"}]}