{"name": "test_login_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <python_test_framework_demo.test_allure_report.TestLogin object at 0x00000210E79C6250>\n\n    @allure.story('密码缺失')\n    def test_login_failure(self):\n        with allure.step('点击用户名'):\n            print('输入用户名')\n        with allure.step('点击密码'):\n            print('输入密码')\n        print('点击登录')\n        with allure.step('点击登录之后登录失败'):\n>           assert '1' == 1\nE           AssertionError: assert '1' == 1\n\ntest_allure_report.py:30: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1618306351653, "stop": 1618306351653}, {"name": "点击密码", "status": "passed", "start": 1618306351653, "stop": 1618306351653}, {"name": "点击登录之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"E:\\TestDev\\python_test_framework_demo\\test_allure_report.py\", line 30, in test_login_failure\n    assert '1' == 1\n"}, "start": 1618306351653, "stop": 1618306351653}], "attachments": [{"name": "stdout", "source": "0d15dd28-4e6d-4b07-893b-c5f25779d450-attachment.txt", "type": "text/plain"}], "start": 1618306351653, "stop": 1618306351654, "uuid": "27de0b3e-fcb6-4b8d-919c-364f0a4e5ea7", "historyId": "c1be10927427fd32313eb62497ab4995", "testCaseId": "b5827c16bd98d49184544ba740c8c531", "fullName": "test_allure_report.TestLogin#test_login_failure", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "story", "value": "密码缺失"}, {"name": "suite", "value": "test_allure_report"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "摩羯座"}, {"name": "thread", "value": "7992-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure_report"}]}