{"name": "test_login_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <python_test_framework_demo.test_allure_report.TestLogin object at 0x000001C9173E5850>\n\n    @allure.story('密码缺失')\n    def test_login_failure(self):\n        with allure.step('点击用户名'):\n            print('输入用户名')\n        with allure.step('点击密码'):\n            print('输入密码')\n        print('点击登录')\n        with allure.step('点击登录之后登录失败'):\n>           assert '1' == 1\nE           AssertionError: assert '1' == 1\n\ntest_allure_report.py:30: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1618288385290, "stop": 1618288385290}, {"name": "点击密码", "status": "passed", "start": 1618288385290, "stop": 1618288385290}, {"name": "点击登录之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"E:\\TestDev\\python_test_framework_demo\\test_allure_report.py\", line 30, in test_login_failure\n    assert '1' == 1\n"}, "start": 1618288385290, "stop": 1618288385290}], "attachments": [{"name": "stdout", "source": "58e0a180-2502-4224-90b1-02da0dda55dd-attachment.txt", "type": "text/plain"}], "start": 1618288385289, "stop": 1618288385291, "uuid": "474e7c40-045a-4153-aa75-922a3620337a", "historyId": "c1be10927427fd32313eb62497ab4995", "testCaseId": "b5827c16bd98d49184544ba740c8c531", "fullName": "test_allure_report.TestLogin#test_login_failure", "labels": [{"name": "story", "value": "密码缺失"}, {"name": "feature", "value": "登录模块"}, {"name": "suite", "value": "test_allure_report"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "摩羯座"}, {"name": "thread", "value": "5772-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure_report"}]}